import { Prompt } from "../models/Prompt.js";

const seedPrompts = [
  {
    title: "Написание статьи",
    body: "Создай структурированную статью на заданную тему.",
    tags: "статья,контент,письмо",
    author: "Admin",
    category: "Контент",
    isPublic: true,
    usageCount: 0,
    version: 1,
  },
  {
    title: "Генератор идей",
    body: "Сгенерируй 5 креативных идей для стартапа.",
    tags: "стартап,идеи,креатив",
    author: "Admin",
    category: "Бизнес",
    isPublic: true,
    usageCount: 0,
    version: 1,
  },
  {
    title: "Сводка новостей",
    body: "Подготовь краткую сводку новостей за день.",
    tags: "новости,сводка,информация",
    author: "Admin",
    category: "Информационные",
    isPublic: true,
    usageCount: 0,
    version: 1,
  },
  {
    title: "Планировщик задач",
    body: "Создай план на день с приоритетами и дедлайнами.",
    tags: "план,задачи,организация",
    author: "Admin",
    category: "Организация",
    isPublic: true,
    usageCount: 0,
    version: 1,
  },
  {
    title: "Генератор заголовков",
    body: "Придумай 5 привлекательных заголовков для блога.",
    tags: "заголовки,контент,маркетинг",
    author: "Admin",
    category: "Контент",
    isPublic: true,
    usageCount: 0,
    version: 1,
  },
  {
    title: "Email шаблон",
    body: "Создай шаблон письма для рассылки клиентам.",
    tags: "email,рассылка,маркетинг",
    author: "Admin",
    category: "Маркетинг",
    isPublic: true,
    usageCount: 0,
    version: 1,
  },
  {
    title: "Сценарий видео",
    body: "Напиши сценарий для короткого видео на YouTube.",
    tags: "видео,сценарий,креатив",
    author: "Admin",
    category: "Контент",
    isPublic: true,
    usageCount: 0,
    version: 1,
  },
  {
    title: "Идеи для социальных сетей",
    body: "Составь 10 идей постов для Instagram.",
    tags: "соцсети,контент,маркетинг",
    author: "Admin",
    category: "Маркетинг",
    isPublic: true,
    usageCount: 0,
    version: 1,
  },
  {
    title: "Учебный план",
    body: "Разработай недельный учебный план по теме.",
    tags: "обучение,план,учёба",
    author: "Admin",
    category: "Образование",
    isPublic: true,
    usageCount: 0,
    version: 1,
  },
  {
    title: "Презентация продукта",
    body: "Создай структуру презентации для нового продукта.",
    tags: "презентация,бизнес,продукт",
    author: "Admin",
    category: "Бизнес",
    isPublic: true,
    usageCount: 0,
    version: 1,
  },
  {
    title: "Описание персонажа",
    body: "Опиши главного героя для истории или игры.",
    tags: "персонаж,креатив,история",
    author: "Admin",
    category: "Креатив",
    isPublic: true,
    usageCount: 0,
    version: 1,
  },
  {
    title: "Пост для блога",
    body: "Напиши пост на тему здорового образа жизни.",
    tags: "блог,здоровье,контент",
    author: "Admin",
    category: "Контент",
    isPublic: true,
    usageCount: 0,
    version: 1,
  },
  {
    title: "Шаблон договора",
    body: "Создай простой шаблон договора для фрилансера.",
    tags: "договор,шаблон,юридическое",
    author: "Admin",
    category: "Бизнес",
    isPublic: true,
    usageCount: 0,
    version: 1,
  },
  {
    title: "Список книг",
    body: "Составь список 10 книг по саморазвитию.",
    tags: "книги,образование,саморазвитие",
    author: "Admin",
    category: "Образование",
    isPublic: true,
    usageCount: 0,
    version: 1,
  },
  {
    title: "Контент для соцсетей",
    body: "Составь план постов для Facebook на месяц.",
    tags: "контент,соцсети,маркетинг",
    author: "Admin",
    category: "Маркетинг",
    isPublic: true,
    usageCount: 0,
    version: 1,
  },
  {
    title: "Тестовое задание",
    body: "Придумай тестовое задание для разработчиков.",
    tags: "тест,разработка,HR",
    author: "Admin",
    category: "Бизнес",
    isPublic: true,
    usageCount: 0,
    version: 1,
  },
  {
    title: "План интервью",
    body: "Создай список вопросов для интервью с кандидатом.",
    tags: "HR,интервью,план",
    author: "Admin",
    category: "Бизнес",
    isPublic: true,
    usageCount: 0,
    version: 1,
  },
  {
    title: "Личный дневник",
    body: "Подготовь шаблон личного дневника для заметок.",
    tags: "дневник,личное,организация",
    author: "Admin",
    category: "Организация",
    isPublic: true,
    usageCount: 0,
    version: 1,
  },
  {
    title: "Контент-план на неделю",
    body: "Составь контент-план для блога на неделю.",
    tags: "контент,план,маркетинг",
    author: "Admin",
    category: "Маркетинг",
    isPublic: true,
    usageCount: 0,
    version: 1,
  },
  {
    title: "Сводка рынка",
    body: "Подготовь сводку текущих трендов на рынке IT.",
    tags: "рынок,IT,тренды",
    author: "Admin",
    category: "Информационные",
    isPublic: true,
    usageCount: 0,
    version: 1,
  },
];

export const seedPromptsToDB = async () => {
  try {
    for (const prompt of seedPrompts) {
      await Prompt.create(prompt);
    }
    console.log("✅ Seed data inserted successfully");
  } catch (err) {
    console.error("❌ Error seeding data:", err);
  }
};
